export const ROUTES = {
  HOME: "/search",
  PRODUCT: `/search`,
  CHECKOUT: "/search",
  CONTACT: "/search",
  TERMS: "/search",
  POLICY: "/search",
  FAQ: "/search",
  FORGET_PASSWORD: "/search",
  ACCOUNT: "/search",
  ORDERS: "/search",
  ACCOUNT_DETAILS: "/search",
  CHANGE_PASSWORD: "/search",
  SHOPS: "/search",
  LOGIN: "/search",
  SIGN_UP: "/search",
  SEARCH: "/search",
  COLLECTIONS: "/search",
  CATEGORY: "/search",
  ORDER: "/search",
};
